### PR TITLE
Disable Intel Sound HDA to eliminate occasional sound cracking

### PR DESCRIPTION
**Pull request by szkocot**
I had issues with youtube videos, where every now and then sound was slightly popping/cracking. This patch is reported by multiple sources to fix these issues and not cause major power draw. It works for me and sound cracking has been eliminated from my 9570.

### CODE REVIEW

**Comment by szkocot** [comment]
It seems like after even temporary fix stopped working. Do you have any idea how to improve it? @JackHack96

**Comment by vikrambombhi** [comment]
Does this issue only occur when you are/aren't using headphones?

**Comment by JackHack96** [comment]
Mmmh I usually use headphones and I don't hear any crackling/popping sound.
The only issue I have is the hissing that's described in the troubleshoot wiki (I still didn't find a better way for fixing that)

**Comment by szkocot** [comment]
I occurs while using external speakers. Same speakers, while connected with aptx bt receiver to the laptop are not having any issues.

**Comment by szkocot** [comment]
It seems, to be only occurring using youtube. I tested both latest chrome and chromium (vaapi experimental snap).

**Comment by JackHack96** [comment]
Uhm... I don't have these issues, watching YouTube from Firefox (with WebRender and other experimental options enabled), connected with a pair of wired earbuds (3.5mm jack)

**Comment by szkocot** [comment]
https://github.com/JackHack96/dell-xps-9570-ubuntu-respin/pull/69/commits/47ed28d424d1ff70355dbde437dac22c6c62346e
Source:
https://wiki.archlinux.org/index.php/PulseAudio/Troubleshooting#Sound_stuttering_when_streaming_over_network
It seemd to be working, but after reboot I am experiencing some stuttering again. I am connected to home wifi (5G, ac) with 250/20 Mbps connection (UPC, about 10ms ping).

**Comment by JackHack96** [comment]
Just for curiosity, did the stuttering happens with Firefox? I have a pretty decent LAN, but a shitty internet connection with just 7/1 Mbps and I don't have any stutter.
I have high quality audio enabled and I also have PulseEffects installed, though I disable it when I'm not listening to music.

**Comment by szkocot** [comment]
Audio cracking/popping/short distortions seem to be happening on both chromium, chrome, and firefox, with speakers and passive headphones (connected with minijack), with or without https://github.com/JackHack96/dell-xps-9570-ubuntu-respin/commit/47ed28d424d1ff70355dbde437dac22c6c62346e only when streaming yt videos.
I've tested UPC internet and LTE hotspot does not matter.
Maybe I am too sound distortion sensitive. I am currently using only high-quality audio config from the master branch.

**Comment by szkocot** [comment]
Yes, you are right. I was doing some research and It seems, that many people have similar issues on 18.04. Most fixes are temporary or depending on actual hardware and configuration. 
This proposed fix seems to survive thru reboot and I don't hear any sound cracks during youtube watching:
https://wiki.archlinux.org/index.php/PulseAudio/Troubleshooting#Glitches.2C_skips_or_crackling

I will close this add and add a note with the proposed solution on the wiki pages.

**Comment by JackHack96** [comment]
Thank you for taking care of it! :+1:

**Comment by szkocot** [comment]
@JackHack96 yeah, I am glad I finally am able to have spotless audio on my xps. I wasn't able to do so on Win10.

**Pull request closed without merging**
